version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # https://gist.github.com/mrw34/c97bb03ea1054afb551886ffc8b63c3b
    command: >
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
  backend:
    depends_on:
      - db
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      # https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired#answer-29397100
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - ../:/home/node/app
    ports:
      - 8080:8080
    command: "node index.js"
  frontend:
    depends_on:
      - backend
    image: "node:16"
    user: "node"
    working_dir: /home/node/app/front-end
    environment:
      NPM_CONFIG_PREFIX: /home/node/.npm-global
    volumes:
      - ../:/home/node/app
    ports:
      - 8100:8100
    command: >
      bash -c "mkdir -p /home/node/.npm-global &&
      export 'PATH=$PATH:/home/node/.npm-global/bin' &&
      npm install -g @ionic/cli &&
      ionic serve --host 0.0.0.0"

volumes:
  dbdata: {}
